"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import {
  Map as MapLibreMap,
  NavigationControl,
  Popup,
  LngLatBounds,
  setWorkerUrl,
  type GeoJSONSource,
  type MapLayerMouseEvent,
  type MapLayerTouchEvent,
} from "maplibre-gl";
import type { Feature, FeatureCollection, LineString, GeoJsonProperties } from "geojson";
import "maplibre-gl/dist/maplibre-gl.css";
import type { Route } from "@/types/route";

// maplibre-gl normally locates its module worker via a bundler-resolved
// `new URL(..., import.meta.url)`. Turbopack's production build doesn't
// reliably emit that asset, so point it at a static copy in public/
// (generated by scripts/copy-maplibre-worker.mjs) instead.
setWorkerUrl("/maplibre-gl-worker.mjs");

const DIFFICULTY_COLORS: Record<string, string> = {
  easy: "#6B8F71",
  moderate: "#E8A33D",
  hard: "#C1542C",
};

const ROUTES_LINE_LAYER = "routes-line";
const ROUTES_CASING_LAYER = "routes-casing";
const ROUTES_HIT_LAYER = "routes-hit";
const ROUTES_SOURCE = "routes";

function routesToFeatureCollection(
  routes: Route[]
): FeatureCollection<LineString, GeoJsonProperties> {
  return {
    type: "FeatureCollection",
    features: routes.map(
      (route, index): Feature<LineString, GeoJsonProperties> => ({
        type: "Feature",
        id: index,
        geometry: {
          type: "LineString",
          coordinates: route.coordinates,
        },
        properties: {
          routeId: route.id,
          name: route.name,
          difficulty: route.difficulty,
          surface: route.surface,
          distanceKm: route.distanceKm,
          elevationGainM: route.elevationGainM,
        },
      })
    ),
  };
}

interface MapViewProps {
  routes: Route[];
  matchedRoutes: Route[];
  selectedRouteId: string | null;
  onSelectRoute: (id: string) => void;
}

export default function MapView({
  routes,
  matchedRoutes,
  selectedRouteId,
  onSelectRoute,
}: MapViewProps) {
  const mapContainerRef = useRef<HTMLDivElement | null>(null);
  const mapRef = useRef<MapLibreMap | null>(null);
  const popupRef = useRef<Popup | null>(null);
  const selectedFeatureId = useRef<number | null>(null);
  const lastMapOriginatedId = useRef<string | null>(null);

  const [mapLoaded, setMapLoaded] = useState(false);

  const featureCollection = useMemo(() => routesToFeatureCollection(routes), [routes]);

  const apiKey = process.env.NEXT_PUBLIC_MAPTILER_KEY;

  // Create the map once.
  useEffect(() => {
    if (!mapContainerRef.current || mapRef.current || !apiKey) return;

    const map = new MapLibreMap({
      container: mapContainerRef.current,
      style: `https://api.maptiler.com/maps/outdoor-v2/style.json?key=${apiKey}`,
      center: [17.1, 48.25],
      zoom: 10,
      attributionControl: { compact: true },
    });

    map.addControl(new NavigationControl({ showCompass: false }), "top-right");
    map.touchZoomRotate.disableRotation();
    map.dragRotate.disable();

    map.on("load", () => {
      map.addSource(ROUTES_SOURCE, {
        type: "geojson",
        data: featureCollection,
      });

      map.addLayer({
        id: ROUTES_CASING_LAYER,
        type: "line",
        source: ROUTES_SOURCE,
        layout: { "line-cap": "round", "line-join": "round" },
        paint: {
          "line-color": "#16231C",
          "line-width": ["case", ["boolean", ["feature-state", "selected"], false], 8, 5],
          "line-opacity": 0.85,
        },
      });

      map.addLayer({
        id: ROUTES_LINE_LAYER,
        type: "line",
        source: ROUTES_SOURCE,
        layout: { "line-cap": "round", "line-join": "round" },
        paint: {
          "line-color": [
            "match",
            ["get", "difficulty"],
            "easy",
            DIFFICULTY_COLORS.easy,
            "moderate",
            DIFFICULTY_COLORS.moderate,
            "hard",
            DIFFICULTY_COLORS.hard,
            "#E8A33D",
          ],
          "line-width": ["case", ["boolean", ["feature-state", "selected"], false], 5, 3],
        },
      });

      // Wide, invisible line purely to make routes easier to tap on touch screens.
      map.addLayer({
        id: ROUTES_HIT_LAYER,
        type: "line",
        source: ROUTES_SOURCE,
        layout: { "line-cap": "round", "line-join": "round" },
        paint: { "line-color": "#000000", "line-width": 24, "line-opacity": 0 },
      });

      const allBounds = routes.reduce((acc, r) => {
        acc.extend(r.bounds[0] as [number, number]);
        acc.extend(r.bounds[1] as [number, number]);
        return acc;
      }, new LngLatBounds());
      if (!allBounds.isEmpty()) {
        map.fitBounds(allBounds, { padding: 48, duration: 0 });
      }

      const showPopup = (e: MapLayerMouseEvent | MapLayerTouchEvent) => {
        const feature = e.features?.[0];
        if (!feature) return;
        const routeId = String(feature.properties?.routeId ?? "");

        lastMapOriginatedId.current = routeId;
        onSelectRoute(routeId);

        popupRef.current?.remove();
        popupRef.current = new Popup({ closeButton: true, offset: 12, className: "rg-popup" })
          .setLngLat(e.lngLat)
          .setHTML(
            `<div class="rg-popup-name">${String(feature.properties?.name ?? "Route")}</div>` +
              `<div class="rg-popup-stats">` +
              `${feature.properties?.distanceKm} km &middot; ${feature.properties?.elevationGainM} m gain &middot; ` +
              `${String(feature.properties?.difficulty)} &middot; ${String(feature.properties?.surface)}` +
              `</div>`
          )
          .addTo(map);
      };

      map.on("click", ROUTES_HIT_LAYER, showPopup);
      map.on("mouseenter", ROUTES_HIT_LAYER, () => {
        map.getCanvas().style.cursor = "pointer";
      });
      map.on("mouseleave", ROUTES_HIT_LAYER, () => {
        map.getCanvas().style.cursor = "";
      });

      setMapLoaded(true);
    });

    mapRef.current = map;

    return () => {
      map.remove();
      mapRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [apiKey]);

  // Force MapLibre to re-measure its canvas whenever the container's actual
  // size changes — defensive against the container reporting zero height
  // at the moment the map was constructed (e.g. during layout transitions).
  useEffect(() => {
    const container = mapContainerRef.current;
    if (!container) return;
    const observer = new ResizeObserver(() => {
      mapRef.current?.resize();
    });
    observer.observe(container);
    return () => observer.disconnect();
  }, []);

  // Keep the source data in sync if routes ever change identity.
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !mapLoaded) return;
    const source = map.getSource(ROUTES_SOURCE) as GeoJSONSource | undefined;
    source?.setData(featureCollection);
  }, [featureCollection, mapLoaded]);

  // Apply filters by hiding non-matching routes via setFilter.
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !mapLoaded) return;
    const visibleIds = matchedRoutes.map((r) => r.id);
    for (const layerId of [ROUTES_CASING_LAYER, ROUTES_LINE_LAYER, ROUTES_HIT_LAYER]) {
      if (map.getLayer(layerId)) {
        map.setFilter(layerId, ["in", ["get", "routeId"], ["literal", visibleIds]]);
      }
    }
  }, [matchedRoutes, mapLoaded]);

  // Reflect external selection (e.g. a sidebar route card) on the map:
  // highlight the matching line, and fly to it unless the selection just
  // originated from clicking that same line on the map.
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !mapLoaded) return;

    if (selectedFeatureId.current !== null) {
      map.setFeatureState({ source: ROUTES_SOURCE, id: selectedFeatureId.current }, { selected: false });
      selectedFeatureId.current = null;
    }

    const originatedFromMapClick = lastMapOriginatedId.current === selectedRouteId;
    lastMapOriginatedId.current = null;

    if (!selectedRouteId) return;
    const index = routes.findIndex((r) => r.id === selectedRouteId);
    if (index === -1) return;

    selectedFeatureId.current = index;
    map.setFeatureState({ source: ROUTES_SOURCE, id: index }, { selected: true });

    if (!originatedFromMapClick) {
      const route = routes[index];
      map.fitBounds(route.bounds, { padding: 64, maxZoom: 15 });
    }
  }, [selectedRouteId, mapLoaded, routes]);

  if (!apiKey) {
    return (
      <div className="flex h-full w-full items-center justify-center bg-forest-soft p-6 text-center">
        <p className="text-sm text-parchment/80">
          Missing NEXT_PUBLIC_MAPTILER_KEY environment variable. Add it to .env.local and restart
          the dev server.
        </p>
      </div>
    );
  }

  return <div ref={mapContainerRef} className="h-full w-full" />;
}
